callbacks:
- callback: InferenceRunner
  split: valid
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: acc/valid
  - metrics: NLLError
    name: loss/valid
- callback: InferenceRunner
  split: test
  subcallbacks:
  - metrics: CategoricalAccuracy
    name: acc/test
  - metrics: NLLError
    name: loss/test
- callback: MaxSaver
  name: acc/valid
- callback: Saver
  max_to_keep: 10
ckpt:
  load_ckpt: true
  load_trainer: false
  name: checkpoints/best_solution.pt
  weight_from_scratch: true
criterion:
  name: nll
dataset:
  binarize: false
  binarize_threshold: 0.1307
  center_crop: 24
  digits_of_interest:
  - 0
  - 1
  - 2
  - 3
  fashion: false
  input_name: image
  n_test_samples: null
  n_valid_samples: null
  name: mnist
  resize: 28
  resize_mode: bilinear
  root: examples/data
  target_name: digit
  train_valid_split_ratio:
  - 0.95
  - 0.05
debug:
  pdb: false
  seed: 42
  set_seed: true
es:
  crossover_size: 10
  est_success_rate: false
  mutation_prob: 0.4
  mutation_size: 20
  n_iterations: 40
  parent_size: 10
  population_size: 40
get_n_params: false
legalization:
  epoch_interval: 9999999999
  legalize: false
  step_interval: 9999999999
model:
  arch:
    down_sample_kernel_size: 6
    encoder_op_list_name: 4x4_ryzxy
    n_blocks: 8
    n_front_share_blocks: 1
    n_front_share_ops: 1
    n_front_share_wires: 1
    n_layers_per_block: 2
    n_wires: 4
    q_layer_name: u3cu3_s0
  load_op_list: false
  name: super_qfc0
  sampler:
    strategy:
      name: plain
  transpile_before_run: false
optimizer:
  lambda_lr: 0.01
  lr: 0.005
  name: adam
  weight_decay: 0.0001
prune:
  eval:
    remove_ops: false
    remove_ops_thres: null
qiskit:
  backend_name: null
  basis_gates_name: null
  est_success_rate: false
  initial_layout: null
  max_jobs: 1
  n_shots: 8192
  noise_model_name: null
  optimization_level: 2
  seed_simulator: 42
  seed_transpiler: 42
  use_qiskit: false
  use_real_qc: false
regularization:
  unitary_loss: false
  unitary_loss_lambda: 0
  unitary_loss_lambda_trainable: false
run:
  bsz: 256
  device: cpu
  n_epochs: 200
  n_warm_epochs: 0
  workers_per_gpu: 8
scheduler:
  name: cosine
trainer:
  act_quant: false
  act_quant_loss: true
  act_quant_loss_lambda: 10
  act_quant_skip_last_node: true
  add_noise: false
  name: q_trainer
verbose: false
